
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int IDENT = 13;
  public static final int FECHACHAVE = 11;
  public static final int PTVIRG = 7;
  public static final int MENOS = 3;
  public static final int NUMBER = 12;
  public static final int MULT = 4;
  public static final int MOD = 6;
  public static final int ABRECHAVE = 10;
  public static final int FECHAPAR = 9;
  public static final int ABREPAR = 8;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "PTVIRG",
  "ABREPAR",
  "FECHAPAR",
  "ABRECHAVE",
  "FECHACHAVE",
  "NUMBER",
  "IDENT"
  };
}

