
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int INTEIRO = 8;
  public static final int MENOS = 4;
  public static final int MULT = 5;
  public static final int MOD = 7;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTVIRG",
  "MAIS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "INTEIRO"
  };
}

